#!/usr/local/bin/python3

from script import * 

def run(sub):
    sb.call(f"python3 .pnpm/{sub}", shell=True)

package_manager = pkg_manager

# subprocess.call(f"python .pnpm/icona/icona {icons_dir}", shell=True)

c = spawn(f"Bundling with {package_manager}...")
# subprocess.call("python3 .pnpm/scripts/sass", shell=True)
shell(f"{package_manager} run build")

c.done()